// KEEP IN SYNC WITH CLIENT CONSTANTS

const GENDERS = {
  F: 'F',
  M: 'M',
  TBD: 'TBD',
};

const LANGUAGES = {
  EN: 'en',
  ES: 'es',
  NL: 'nl',
};

const SPORTS = {
  FOOTBALL: 'FOOTBALL',
  VOLLEYBALL: 'VOLLEYBALL',
  BEACH_VOLLEYBALL: 'BEACH_VOLLEYBALL',
  TENNIS: 'TENNIS',
  TABLE_TENNIS: 'TABLE_TENNIS',
  ABSOLUTE_FRISBEE: 'ABSOLUTE_FRISBEE',
  BASKETBALL: 'BASKETBALL',
  BADMINTON: 'BADMINTON',
};

module.exports = {
  GENDERS,
  LANGUAGES,
  SPORTS,
};
