// KEEP IN SYNC WITH CLIENT CONSTANTS

const GENDERS = {
  F: 'F',
  M: 'M',
  TBD: 'TBD',
};

const LANGUAGES = {
  EN: 'en',
  ES: 'es',
  NL: 'nl',
};

const SPORTS = {
  FOOTBALL: 'FOOTBALL',
  VOLLEYBALL: 'VOLLEYBALL',
  BEACH_VOLLEYBALL: 'BEACH_VOLLEYBALL',
  TENNIS: 'TENNIS',
  TABLE_TENNIS: 'TABLE_TENNIS',
  ABSOLUTE_FRISBEE: 'ABSOLUTE_FRISBEE',
  BASKETBALL: 'BASKETBALL',
  BADMINTON: 'BADMINTON',
};

const ACTIVITY_STATUSES = {
  ACTIVE: 'ACTIVE',
  CANCELED: 'CANCELED',
  FINISHED: 'FINISHED',
  DELETED: 'DELETED',
};

const NOTIFICATION_TYPES = {
  NEW_ACTIVITY: 'NEW_ACTIVITY',
  ACTIVITY_CANCELED: 'ACTIVITY_CANCELED',
  ACTIVITY_RECREATED: 'ACTIVITY_RECREATED',
  ATTENDEE_ADDED: 'ATTENDEE_ADDED',
  ATTENDEE_REMOVED: 'ATTENDEE_REMOVED',
};

module.exports = {
  GENDERS,
  LANGUAGES,
  SPORTS,
  ACTIVITY_STATUSES,
  NOTIFICATION_TYPES,
};
